events {
  worker_connections 1024;
}

http {
  upstream orders_upstream {
    server orders-service:3000;
    server orders-service-2:3000;
  }

  upstream users_upstream {
    server microservices-lab4-users-service-1:3000;
  }

  upstream products_upstream {
    server microservices-lab4-products-service-1:3000;
  }

  upstream payments_upstream {
    server microservices-lab4-payments-service-1:3000;
  }

  server {
    listen 8080;
    server_name _;

    location /services/orders/api/ {
      proxy_pass http://orders_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /services/users/api/ {
      proxy_pass http://users_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /services/products/api/ {
      proxy_pass http://products_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /services/payments/api/ {
      proxy_pass http://payments_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
